# Generated by Django 5.1.1 on 2025-03-02 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_manager_id_alter_manager_managerid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='waiter',
            name='first_login',
            field=models.BooleanField(default=True),
        ),
    ]
