# Generated by Django 5.1.1 on 2024-12-28 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Managers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manager',
            old_name='email',
            new_name='emailtest',
        ),
    ]
