# Generated by Django 5.1.1 on 2024-12-28 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Managers', '0002_rename_email_manager_emailtest'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Manager',
            new_name='Managers',
        ),
    ]
