# Generated by Django 5.1.1 on 2024-12-28 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Managers', '0003_rename_manager_managers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='managers',
            old_name='emailtest',
            new_name='email',
        ),
    ]
