# Generated by Django 5.1.1 on 2024-12-28 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Managers', '0004_rename_emailtest_managers_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Managers',
            new_name='Manager',
        ),
    ]
