# Generated by Django 5.1.1 on 2025-01-21 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Managers', '0005_rename_managers_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='managerId',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
