# Generated by Django 5.1.1 on 2025-01-21 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Managers', '0007_manager_groups_manager_is_active_manager_is_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='user_permissions',
        ),
    ]
