# Generated by Django 5.1.1 on 2025-01-22 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Managers', '0010_remove_manager_groups_remove_manager_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
