# Generated by Django 5.1.1 on 2025-01-22 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Managers', '0012_manager_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
    ]
