# Generated by Django 5.1.1 on 2025-01-22 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Managers', '0013_manager_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='has_perm',
            field=models.BooleanField(default=True),
        ),
    ]
