# Generated by Django 5.1.1 on 2025-01-22 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Managers', '0014_manager_has_perm'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manager',
            old_name='has_perm',
            new_name='has_permission',
        ),
    ]
