# Generated by Django 5.1.1 on 2024-12-29 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratingID', models.CharField(max_length=50, unique=True)),
                ('tableNo', models.CharField(max_length=50)),
                ('score', models.CharField(max_length=50)),
                ('comments', models.CharField(max_length=100)),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('customer', models.CharField(max_length=50)),
            ],
        ),
    ]
