# Generated by Django 5.1.1 on 2024-12-31 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0003_alter_customer_email'),
        ('Ratings', '0001_initial'),
        ('Tables', '0003_alter_reservation_tableno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='id',
        ),
        migrations.AlterField(
            model_name='rating',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Customers.customer'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='ratingID',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='score',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='rating',
            name='tableNo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tables.table'),
        ),
    ]
