# Generated by Django 5.1.1 on 2024-12-31 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tables', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('reservationId', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('size', models.PositiveIntegerField()),
                ('customer_name', models.CharField(max_length=50)),
                ('tableNo', models.CharField(max_length=10)),
                ('comments', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=50)),
                ('time_booked', models.DateTimeField()),
                ('customerId', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='table',
            name='id',
        ),
        migrations.AlterField(
            model_name='table',
            name='capacity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='table',
            name='tableNo',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
