# Generated by Django 5.1.1 on 2024-12-31 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tables', '0002_reservation_remove_table_id_alter_table_capacity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='tableNo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tables.table'),
        ),
    ]
