# Generated by Django 5.1.1 on 2024-12-31 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='id',
        ),
        migrations.AlterField(
            model_name='customer',
            name='customerId',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
