# Generated by Django 5.1.1 on 2024-12-31 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0002_remove_customer_id_alter_customer_customerid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.CharField(max_length=100),
        ),
    ]
