# Generated by Django 5.1.1 on 2025-02-11 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('reservationId', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('size', models.IntegerField()),
                ('comments', models.CharField(max_length=30)),
                ('duration', models.CharField(max_length=20)),
                ('time_booked', models.DateTimeField(auto_now_add=True)),
                ('customer_name', models.CharField(max_length=50)),
                ('tableNo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.table')),
            ],
        ),
    ]
