# Generated by Django 5.1.1 on 2025-02-11 17:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_alter_reservation_reservationid'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='reservation_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
