# Generated by Django 5.1.1 on 2025-02-11 22:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_reservation_reservation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='endTime',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='reservation',
            name='startTime',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
