# Generated by Django 5.1.1 on 2025-02-17 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_alter_reservation_endtime_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('foodId', models.CharField(blank=True, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('food_name', models.CharField(max_length=50)),
                ('ingredients', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(choices=[('Main Meal', 'Main Meal'), ('Fast Food', 'Fast Food'), ('Sides', 'Sides')], default='Main Meal', max_length=50)),
                ('duration', models.CharField(max_length=10)),
                ('price', models.CharField(max_length=10)),
                ('allergen', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='food_images/')),
            ],
        ),
    ]
