# Generated by Django 5.1.1 on 2025-02-17 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_food'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='foodId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
