# Generated by Django 5.1.1 on 2025-02-17 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0009_alter_food_foodid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('drinkId', models.AutoField(primary_key=True, serialize=False)),
                ('drink_name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('alcoholConc', models.CharField(max_length=20)),
                ('price', models.CharField(max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='drink_images/')),
                ('category', models.CharField(choices=[('Alcohol', 'Alcohol'), ('Soft Drinks', 'Soft Drinks'), ('Shakes', 'Shakes')], default='Soft Drinks', max_length=50)),
            ],
        ),
    ]
