# Generated by Django 5.1.1 on 2025-02-19 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0010_drink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='category',
            field=models.CharField(choices=[('Main Meal', 'Main Meal'), ('Fast Food', 'Fast Food'), ('Sides', 'Sides'), ('Deserts', 'Deserts')], default='Main Meal', max_length=50),
        ),
    ]
