# Generated by Django 5.1.1 on 2025-02-19 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0011_alter_food_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='calories',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='calories',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='drink',
            name='alcoholConc',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='drink',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
