# Generated by Django 5.1.1 on 2025-02-19 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0012_drink_calories_food_calories_alter_drink_alcoholconc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='ingredients',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
