# Generated by Django 5.1.1 on 2025-03-05 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0014_favourite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favourite',
            name='drink_id',
        ),
    ]
