# Generated by Django 5.1.1 on 2025-03-05 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0015_remove_favourite_drink_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='favourite',
            name='drink_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.drink'),
        ),
    ]
