# Generated by Django 5.1.1 on 2025-03-10 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0016_favourite_drink_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='fav_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='fav_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
