# Generated by Django 5.1.1 on 2025-03-10 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0018_basket'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=10)),
                ('spice_level', models.CharField(blank=True, choices=[('Not Spicy', 'Not Spicy'), ('Spicy', 'Spicy'), ('Very Spicy', 'Very Spicy')], default='Not Spicy', max_length=50, null=True)),
                ('food_sauce', models.CharField(blank=True, choices=[('Ketchup', 'Ketchup'), ('Mayo', 'Mayo'), ('Sweet Chilli', 'Sweet Chilli')], default='Ketchup', max_length=50, null=True)),
                ('protein', models.CharField(blank=True, choices=[('Chicken', 'Chicken'), ('Beef', 'Beef'), ('Fish', 'Fish')], default='Chicken', max_length=50, null=True)),
                ('desert_sauce', models.CharField(blank=True, choices=[('Toffee', 'Toffee'), ('Caramel', 'Caramel'), ('Strawberry', 'Strawberry')], default='Toffee', max_length=50, null=True)),
                ('drink_size', models.CharField(blank=True, choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large')], default='Small', max_length=50, null=True)),
                ('has_ice', models.BooleanField(default=False)),
                ('notes', models.CharField(blank=True, max_length=100, null=True)),
                ('basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.basket')),
                ('drink_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.drink')),
                ('food_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.food')),
            ],
        ),
    ]
