# Generated by Django 5.1.1 on 2025-03-15 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0020_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='customer_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
