# Generated by Django 5.1.1 on 2025-03-16 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0021_rating_customer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='soup_choice',
            field=models.CharField(blank=True, choices=[('Egusi', 'Egusi'), ('Ogbono', 'Ogbono'), ('Abula', 'Abula')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='desert_sauce',
            field=models.CharField(blank=True, choices=[('Toffee', 'Toffee'), ('Caramel', 'Caramel'), ('Strawberry', 'Strawberry')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='drink_size',
            field=models.CharField(blank=True, choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='food_sauce',
            field=models.CharField(blank=True, choices=[('Ketchup', 'Ketchup'), ('Mayo', 'Mayo'), ('Sweet Chilli', 'Sweet Chilli')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='protein',
            field=models.CharField(blank=True, choices=[('Chicken', 'Chicken'), ('Beef', 'Beef'), ('Fish', 'Fish')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='spice_level',
            field=models.CharField(blank=True, choices=[('Not Spicy', 'Not Spicy'), ('Spicy', 'Spicy'), ('Very Spicy', 'Very Spicy')], max_length=50, null=True),
        ),
    ]
