# Generated by Django 5.1.1 on 2025-03-17 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0024_order_order_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='basket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.basket'),
        ),
    ]
