# Generated by Django 5.1.1 on 2025-03-18 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0025_alter_orderitem_basket'),
        ('users', '0004_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='waiter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.waiter'),
        ),
    ]
