# Generated by Django 5.1.1 on 2025-03-20 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0026_basket_waiter'),
    ]

    operations = [
        migrations.CreateModel(
            name='KitchenZone',
            fields=[
                ('zoneId', models.AutoField(primary_key=True, serialize=False)),
                ('active_orders', models.PositiveIntegerField(default=0)),
                ('total_remaining_time', models.PositiveBigIntegerField(default=0)),
            ],
        ),
    ]
