# Generated by Django 5.1.1 on 2025-03-21 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0027_kitchenzone'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='assigned_zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.kitchenzone'),
        ),
    ]
