# Generated by Django 5.1.1 on 2025-03-21 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0028_order_assigned_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Delayed', 'Delayed'), ('Assigned', 'Assigned'), ('Ready', 'Ready'), ('Delivered', 'Delivered')], default='Pending', max_length=50),
        ),
    ]
