# Generated by Django 5.1.1 on 2025-03-22 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0029_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Assigned', 'Assigned'), ('Ready', 'Ready'), ('Delivered', 'Delivered')], default='Pending', max_length=50),
        ),
    ]
