# Generated by Django 5.1.1 on 2025-03-23 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0030_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kitchenzone',
            name='total_remaining_time',
        ),
    ]
