# Generated by Django 5.1.1 on 2025-03-24 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0032_inventory_stocklevel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stocklevel',
            name='ingredient',
        ),
        migrations.RemoveField(
            model_name='stocklevel',
            name='kitchen_zone',
        ),
        migrations.DeleteModel(
            name='Inventory',
        ),
        migrations.DeleteModel(
            name='StockLevel',
        ),
    ]
