# Generated by Django 5.1.1 on 2024-12-31 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0003_alter_customer_email'),
        ('Orders', '0001_initial'),
        ('Products', '0004_inventory'),
        ('Tables', '0003_alter_reservation_tableno'),
        ('Waiters', '0002_remove_waiter_id_alter_waiter_waiterid'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customerId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Customers.customer'),
        ),
        migrations.AddField(
            model_name='order',
            name='tableNo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Tables.table'),
        ),
        migrations.AddField(
            model_name='order',
            name='waiterId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Waiters.waiter'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='drinkID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Products.drink'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='foodID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Products.food'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_placed_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
