# Generated by Django 5.1.1 on 2024-12-31 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('itemID', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('description', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('in_stock', 'In Stock'), ('low', 'Low'), ('out_of_stock', 'Out of Stock')], max_length=20)),
                ('last_updated', models.CharField(max_length=50)),
                ('updated_by', models.DateTimeField()),
            ],
        ),
    ]
