# Generated by Django 5.1.1 on 2024-12-31 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_inventory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inventory',
        ),
        migrations.RemoveField(
            model_name='drink',
            name='id',
        ),
        migrations.RemoveField(
            model_name='food',
            name='id',
        ),
        migrations.AddField(
            model_name='drink',
            name='drinkID',
            field=models.CharField(default=1, max_length=20, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='food',
            name='calories',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='food',
            name='foodID',
            field=models.CharField(default=1, max_length=20, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='drink',
            name='alcoholConc',
            field=models.CharField(max_length=10),
        ),
    ]
